name: Terraform Plan

on:
  pull_request:

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform-infrastructure
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform-infrastructure
        run: terraform plan
